# Settings that the LAMMPS build will import when this package library is used
#
# Ubuntu 18.04 installation of VTK7 library:
# ------------------------------------------
#
# Execute the following installation command:
#
# $ sudo apt-get install libvtk7-dev
#
vtk_SYSINC = -I/usr/include/vtk-8.2
vtk_SYSLIB = -lvtkCommonCore-8.2 -lvtkIOCore-8.2 -lvtkIOXML-8.2 -lvtkIOLegacy-8.2 -lvtkCommonDataModel-8.2 -lvtkIOParallelXML-8.2
vtk_SYSPATH = -L/usr/lib/x86_64-linux-gnu
