containers:
  extra_basics: .
  basic:
    cpl: # base container identifier
      os:
        distro: ubuntu
        version: 24.04
      mpi:
        implementation: mpich
        version: 4.2.2
      framework:
        definition: cpl
        version: 712bb02a
  projects:
    cpl-openfoam-lammps:
      base_container: cpl
      definition: projects/cpl-openfoam-lammps.def
      build_args:
        foam_extend_version:
          - 5.0
        lammps_version:
          - fcbc37d5a40e6dbd91148921378d28fca5294675 # MUST be long hash
        vtk_version:
          - 8.2.0
pull:
  try_to_pull: true
  protocol: "oras"
  scope: "ghcr.io/foamscience"
